"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Interchange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    T_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    D_FIELD_NUMBER: builtins.int
    t: builtins.str
    id: builtins.str
    d: builtins.str
    def __init__(
        self,
        *,
        t: builtins.str = ...,
        id: builtins.str = ...,
        d: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["d", b"d", "id", b"id", "t", b"t"]) -> None: ...

global___Interchange = Interchange

@typing.final
class GuildInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GuildInfo = GuildInfo

@typing.final
class GuildMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AVAILABLE_FIELD_NUMBER: builtins.int
    PRESENCES_FIELD_NUMBER: builtins.int
    available: builtins.bool
    presences: builtins.int
    def __init__(
        self,
        *,
        available: builtins.bool = ...,
        presences: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available", b"available", "presences", b"presences"]) -> None: ...

global___GuildMetadata = GuildMetadata
