[package]
name = "api"
version = "0.0.0"
edition = "2024"

[dependencies]
snowdon = "0.2.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-native-tls", "postgres", "macros", "chrono"] }
tokio = { version = "1.45.0", features = ["full"] }
